name: "Ai release notes"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  read-write:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
